/*
 * SnapHeater U1
 * Copyright (c) 2026 Damian Borkowski
 * SPDX-License-Identifier: MIT
 */

package com.alphastudio.snapheateru1.model

data class HeaterSnapshot(
    val firmwareVersion: String = "0.2.0-dev",
    val chamberC: Int = 31,
    val ptcC: Int = 38,
    val targetC: Int = 45,
    val safetyScore: Int = 62,
    val setupValidationPassed: Boolean = false,
    val outputSafetyLatchArmed: Boolean = false,
    val heaterLocked: Boolean = true,
    val gpioProbeLocked: Boolean = true,
    val fanOn: Boolean = false,
    val moonraker: String = "Read-only / waiting",
    val ble: String = "Advertising",
    val material: String = "PETG",
    val printerState: String = "standby",
    val printProgressPct: Int = 0,
    val activeTool: String = "extruder0",
    val activeMaterial: String = "PETG",
    val materialAdvice: String = "PETG profile selected",
    val mode: AppMode = AppMode.AutoStandby,
    val manualFanAssist: Boolean = false,
    val preheatHeatSoakMin: Int = 15,
    val dryingTimeMin: Int = 120,
    val temperingDurationMin: Int = 45,
    val lastConfirmedSettings: String = "No mode settings confirmed",
    val warmupEtaMin: Int = 12,
    val heatSoakEnabled: Boolean = true,
    val heatSoakReady: Boolean = false,
    val stabilityScore: Int = 76,
    val printRiskScore: Int = 28,
    val printRiskMessage: String = "Low risk with current target",
    val virtualDoorDetectionEnabled: Boolean = true,
    val virtualDoorOpen: Boolean = false,
    val virtualDoorPending: Boolean = false,
    val autoMaterialProfileEnabled: Boolean = true,
    val mismatchWarningEnabled: Boolean = true,
    val plaProtectionEnabled: Boolean = true,
    val antiWarpEnabled: Boolean = true,
    val largePrintProtectionEnabled: Boolean = true,
    val safeOvernightEnabled: Boolean = false,
    val pauseHoldEnabled: Boolean = true,
    val smartResumeEnabled: Boolean = true,
    val startPrintWarningEnabled: Boolean = true,
    val airflowDetectionEnabled: Boolean = true,
    val airflowWarningPending: Boolean = false,
    val filterLifePct: Int = 18,
    val filterWarningPending: Boolean = false,
    val heaterWearPct: Int = 7,
    val estimatedEnergyWh: Int = 42,
    val sessionEnergyWh: Int = 11,
    val tempHistoryEnabled: Boolean = true,
    val incidentReportEnabled: Boolean = true,
    val localRecipesEnabled: Boolean = true,
    val activeRecipeName: String = "PETG Balanced",
    val scheduledPreheatEnabled: Boolean = false,
    val localOnlyMode: Boolean = true,
    val demoModeEnabled: Boolean = true,
    val showcaseModeEnabled: Boolean = false,
    val symbiontModeEnabled: Boolean = false,
    val symbiontVentilationAllowed: Boolean = false,
    val otaRollbackReady: Boolean = false,
)
