#!/bin/sh
set -eu
root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
api="$root/main/api_server.c"
boot="$root/main/app_main.c"
defaults="$root/sdkconfig.defaults"
parts="$root/partitions.csv"

grep -q 'esp_ota_get_next_update_partition(NULL)' "$api"
grep -q 'req->content_len.*partition->size' "$api"
grep -q 'esp_ota_begin(partition, OTA_WITH_SEQUENTIAL_WRITES' "$api"
grep -q 'esp_ota_write(update' "$api"
grep -q 'esp_ota_end(update)' "$api"
grep -q 'esp_ota_get_partition_description(partition' "$api"
grep -q 'esp_partition_erase_range(partition, 0, partition->erase_size)' "$api"
grep -q 'esp_ota_set_boot_partition(partition)' "$api"
grep -q '"SnapHeater_U1"' "$api"
grep -q '"dragonbreath"' "$api"
grep -q '"panda_breath"' "$api"
grep -q 'maintenance_acquire()' "$api"
grep -q 'cleanup(maintenance_release)' "$api"
grep -q 'reject_unauthorized(req)' "$api"
grep -q 'CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE=y' "$defaults"
grep -q 'shu1_safety_wait_healthy' "$boot"
grep -q 'esp_ota_mark_app_valid_cancel_rollback' "$boot"
grep -Eq '^app0,[[:space:]]+app,[[:space:]]+ota_0,[[:space:]]+0x10000,[[:space:]]+0x1[Ee]0000' "$parts"
grep -Eq '^app1,[[:space:]]+app,[[:space:]]+ota_1,[[:space:]]+0x1[fF]0000,[[:space:]]+0x1[Ee]0000' "$parts"

description_line="$(grep -n 'esp_ota_get_partition_description(partition' "$api" | head -1 | cut -d: -f1)"
identity_line="$(grep -n '!accepted_image_identity(&image)' "$api" | head -1 | cut -d: -f1)"
boot_line="$(grep -n 'esp_ota_set_boot_partition(partition)' "$api" | head -1 | cut -d: -f1)"
test "$description_line" -lt "$identity_line"
test "$identity_line" -lt "$boot_line"

healthy_line="$(grep -n 'shu1_safety_wait_healthy' "$boot" | cut -d: -f1)"
valid_line="$(grep -n 'esp_ota_mark_app_valid_cancel_rollback' "$boot" | cut -d: -f1)"
test "$healthy_line" -lt "$valid_line"

echo "SnapHeater OTA static contract: PASS"
