"""Feed JSON generated by the real Kotlin builders through both production parsers.

First run Android gradlew testDebugUnitTest. Transport auth/arbitration and
physical control-loop faults are covered separately; no hardware is energized.
"""
import json
import unittest
import test_audit_regressions as audit
from test_audit_regressions import COMMON, ROOT, function, source

FIXTURES = ROOT / "apps/android/SnapHeaterU1/app/build/control-fixtures"


class AppFirmwareContractTests(unittest.TestCase):
    compile = audit.AuditRegressionTests.compile

    def test_legacy_smart_resume_removed_but_user_pause_remains(self):
        paths=list((ROOT / "main").glob("*.[ch]"))
        paths+=list((ROOT / "apps/android/SnapHeaterU1/app/src/main").rglob("*.kt"))
        paths+=list((ROOT / "apps/android/SnapHeaterU1/app/src/main/res").rglob("*.xml"))
        for path in paths:
            text=path.read_text(encoding="utf-8")
            for retired in ("smart_resume", "smartResume", "resume_recover"):
                self.assertNotIn(retired,text,str(path))
        self.assertIn('"pause_job"',source("job_commands.h"))
        self.assertIn("if (!st->user_paused) update_heat_soak",source("safety.c"))

    def test_pause_preserves_job_timers_and_off_cancels_resume(self):
        self.compile(COMMON + r'''
#include "job_commands.h"
''' + function("app_state.c", "void shu1_settings_stop(") + r'''
int main(void) {
 shu1_settings_t s={0};
 s.work_on=true; s.drying_running=true; s.drying_end_ms=61000;
 s.tempering_start_ms=500; s.tempering_end_ms=60500;
 cJSON *pause=cJSON_Parse("{\"pause_job\":true}");
 cJSON *resume=cJSON_Parse("{\"pause_job\":false}");
 shu1_finish_job_command(&s,pause,1000);
 assert(s.user_paused && s.work_on && s.drying_running && s.drying_end_ms==61000);
 shu1_finish_job_command(&s,pause,2000);
 assert(s.user_pause_started_ms==1000);
 shu1_finish_job_command(&s,resume,11000);
 assert(!s.user_paused && s.drying_end_ms==71000);
 assert(s.tempering_start_ms==10500 && s.tempering_end_ms==70500);
 assert(s.preheat_end_ms==0);
 shu1_finish_job_command(&s,resume,12000);
 assert(s.drying_end_ms==71000);
 shu1_finish_job_command(&s,pause,13000);
 shu1_settings_stop(&s);
 shu1_finish_job_command(&s,resume,20000);
 assert(!s.work_on && !s.user_paused && !s.drying_running);
 cJSON_Delete(pause); cJSON_Delete(resume);
 return 0;
}
''', json=True)

    def test_real_kotlin_payloads_through_both_firmware_parsers(self):
        self.assertTrue((FIXTURES / "auto.json").exists(),
                        "Run apps/android/SnapHeaterU1/gradlew testDebugUnitTest first")
        fixtures = {p.stem: p.read_text(encoding="utf-8") for p in FIXTURES.glob("*.json")}
        common = COMMON + r'''
#include "job_commands.h"
static bool g_auto_print_context_seen;
static int64_t esp_timer_get_time(void) { return 1000000; }
static void shu1_event_log_add(const char *a, const char *b, const char *c) {}
static void shu1_ble_notify_status_now(void) {}
''' + function("app_state.c", "void shu1_settings_stop(")
        common += function("ble_control.c", "static int clamp_i(")
        common += function("ble_control.c", "static int json_int_clamp(")
        common += function("ble_control.c", "static bool json_bool(")
        common += function("ble_control.c", "static void apply_drying_start_stop(")
        common += function("safety.c", "static int clamp_target(")
        common += function("safety.c", "static int effective_target_for_settings(")
        common += function("safety.c", "static void update_tempering(")
        for transport in ("ble_control.c", "api_server.c"):
            text = source(transport)
            start = text.index("    if (shu1_explicit_job_start(root)) shu1_settings_stop(&st);")
            end = text.index("    if ((st.work_on || st.scheduled_preheat_enabled)", start)
            # Unmodified production settings parser, before authorization/commit.
            program = common + "\nstatic shu1_settings_t parse(shu1_settings_t st, cJSON *root) {\n"
            program += text[start:end] + "\nreturn st; }\n"
            for name, payload in fixtures.items():
                program += f"static const char *{name}_json = {json.dumps(payload)};\n"
            program += r'''
static shu1_settings_t run(shu1_settings_t st, const char *json) {
 cJSON *root=cJSON_Parse(json); assert(root);
 st=parse(st,root); cJSON_Delete(root); return st;
}
int main(void) {
 shu1_settings_t initial={0};
 initial.work_on=true; initial.preheat_running=true; initial.drying_running=true;
 initial.keep_warm_active=true; initial.tempering_phase=SHU1_TEMPERING_ACTIVE;
 shu1_settings_t s=run(initial,auto_json);
 assert(s.work_on && s.work_mode==SHU1_MODE_AUTO && !s.tempering_enabled);
 assert(!s.preheat_running && !s.drying_running && !s.keep_warm_active);
 assert(s.tempering_phase==SHU1_TEMPERING_IDLE);
 s=run(initial,auto_temper_json);
 assert(s.work_on && s.tempering_enabled && s.finish_conditioning_mode==SHU1_FINISH_TEMPERING);
 s=run(initial,preheat_json);
 assert(s.work_on && s.preheat_running && !s.drying_running);
 assert(effective_target_for_settings(&s)==50 && s.preheat_hold_min==12);
 s=run(initial,drying_json);
 assert(s.work_on && s.drying_running && !s.preheat_running);
 assert(s.drying_end_ms==1000+90*60000 && effective_target_for_settings(&s)==50);
 s=run(initial,tempering_json);
 assert(s.work_on && s.work_mode==SHU1_MODE_POWER_ON);
 assert(s.tempering_phase==SHU1_TEMPERING_ACTIVE && s.tempering_start_temp_c==50);
 assert(s.tempering_end_temp_c==35 && !s.preheat_running && !s.drying_running);
 update_tempering(&s,1000+15*60000);
 assert(s.tempering_current_target_c==43 && s.work_on);
 update_tempering(&s,1000+30*60000);
 assert(!s.work_on && s.tempering_complete_pending);
 shu1_settings_t idle={0};
 idle.heat_soak_enabled=true; idle.pla_protection_enabled=true;
 idle.temp_history_enabled=true;
 s=run(idle,preferences_json);
 assert(!s.work_on && !s.scheduled_preheat_enabled && !s.preheat_running && !s.drying_running);
 assert(!s.heat_soak_enabled && !s.pla_protection_enabled);
 assert(!s.temp_history_enabled);
 s=run(idle,schedule_json);
 assert(!s.work_on && s.scheduled_preheat_enabled);
 assert(s.scheduled_preheat_delay_min==17 && s.scheduled_preheat_target_c==43 && s.scheduled_preheat_hold_min==11);
 s=run(s,cancel_schedule_json); assert(!s.scheduled_preheat_enabled && !s.work_on);
 return 0;
}
'''
            with self.subTest(transport=transport):
                self.compile(program, json=True)

    def test_off_authorization_and_new_job_commit_order(self):
        for transport, marker in (("api_server.c", 'static esp_err_t settings_post_handler('),
                                  ("ble_control.c", 'static int handle_control_write(')):
            text = function(transport, marker)
            self.assertLess(text.index("apply_safe_stop(&st)"), text.index("shu1_finish_job_command"))
            self.assertLess(text.index("shu1_finish_job_command"), text.index("if ((st.work_on || st.scheduled_preheat_enabled)"))
            self.assertIn("shu1_control_start_allowed()", text)
            self.assertIn("has_valid_revision(root)", text)
            self.assertIn("shu1_control_authorize(", text)

    def test_rest_auth_probe_is_read_only_and_credentials_are_not_plaintext(self):
        handler = function("api_server.c", "static esp_err_t auth_check_get_handler(")
        self.assertIn("reject_unauthorized", handler)
        self.assertNotIn("shu1_state_update", handler)
        path = ROOT / "apps/android/SnapHeaterU1/app/src/main/java/com/alphastudio/snapheateru1/data"
        vault = (path / "RestCredentials.kt").read_text(encoding="utf-8")
        self.assertIn("AndroidKeyStore", vault)
        self.assertIn("AES/GCM/NoPadding", vault)
        self.assertNotIn('putString(address, token)', vault)
